services:
  #ansible:
  #  hostname: ansible
  #  container_name: ansible
  #  image: python:13
  #  networks:
  #    - ansible-net
  #  command: tail -f /dev/null
  #  volumes:
  #    - ./ansible-setup.sh:/ansible-setup.sh

  host1:
    privileged: true
    hostname: host1
    container_name: host1
    command: /usr/lib/systemd/systemd --system --unit=multi-user.target
    build:
      context: .
      dockerfile: debian.dockerfile
    networks:
      - ansible-net
   

  host2:
    privileged: true
    hostname: host2
    container_name: host2
    build:
      context: .
      dockerfile: debian.dockerfile
    command: /usr/lib/systemd/systemd --system --unit=multi-user.target
    networks:
      - ansible-net
    

  host3:
    privileged: true
    hostname: host3
    container_name: host3
    build:
      context: .
      dockerfile: redhat.dockerfile
    command: /usr/lib/systemd/systemd --system --unit=multi-user.target
    networks:
      - ansible-net
    
  host4:     
    privileged: true
    hostname: host4
    container_name: host4
    build:
      context: .
      dockerfile: redhat.dockerfile
    command: /usr/lib/systemd/systemd --system --unit=multi-user.target
    networks:
      - ansible-net
  


networks:
  ansible-net:
    driver: bridge
    name: ansible-net
